name: Send Notification

on:
  schedule:
    - cron: "0 10 * * *"
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Tweet today's Wordle
        run: |
            pwd
            ls -al
            python3 wordle.py "${{secrets.WEBHOOK}}"
